config/routes.rb
Rails.application.routes.draw do
  root "shortlist#index"

  resources :open_positions_lists
  resources :shortlist
  
  resources :open_positions_lists do
    collection do
      post :import
    end
  end
  
  # get 'static_pages/shortlist'

  get 'static_pages/about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # root "shortlist#index"

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/open_positions_list.rb
class OpenPositionsList < ApplicationRecord
    
    # validates_length_of :summary, :minimum => 5, :too_short => "Die Beschreibung ist leider zu kurz, bitte mindestens 5 Zeichen verwenden."
    # validates_length_of :description, :minimum => 25, :too_short => "Die Beschreibung ist leider zu kurz, bitte mindestens 25 Zeichen verwenden."
    
    scope :client,     -> (client)     { where client: client }
    scope :shortlist,  -> (shortlist)  { where shortlist: shortlist }
    scope :category,   -> (category)   { where category: category }
    scope :updated_at, -> (updated_at) { where updated_at: updated_at }
    scope :costmodel,  -> (costmodel)  { where costmodel: costmodel }
    scope :state,      -> (state)      { where state: state }
    scope :prio,       -> (prio)       { where prio: prio }
    
    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |opl|
          csv << opl.attributes.values
        end
      end
    end
    
    def self.to_xls(options = {})
      CSV.generate(options) do |xls|
        xls << column_names
        all.each do |opl|
          xls << opl.attributes.values
        end
      end
    end
    
    def self.import(file)
      spreadsheet = Roo::Spreadsheet.open(file.path)
      spreadsheet.default_sheet = spreadsheet.sheets.first
      header = spreadsheet.row(3)
      (4..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        open_positions_lists = find_by(id: row["id"]) || new
        open_positions_lists.attributes = row.to_hash
        open_positions_lists.save!
      end
    end
    
    # def self.import(file)
    #   spreadsheet = Roo::Spreadsheet.open(file.path)
    #   header = spreadsheet.row(1)
    #   (2..spreadsheet.last_row).each do |i|
    #     row = Hash[[header, spreadsheet.row(i)].transpose]
    #     open_positions_lists = find_by(id: row["id"]) || new
    #     open_positions_lists.attributes = row.to_hash
    #     open_positions_lists.save!
    #   end
    # end 
    
end

app/controllers/open_positions_lists_controller.rb
class OpenPositionsListsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_open_positions_list, only: [:show, :edit, :update, :destroy]
  before_action :open_position_list_number_new, only: [:new]

  def shortlist
    @on_shortlist = OpenPositionsList.where(nil)
    @on_shortlist = OpenPositionsList.where(shortlist: true)
  end
  
  # GET /open_positions_lists
  # GET /open_positions_lists.json
  
  
  
  def index
    @open_positions_lists = OpenPositionsList.all
    @open_positions_lists = OpenPositionsList.order(sort_column + " " + sort_direction)
    @open_positions_lists = OpenPositionsList.where(nil)
    filtering_params(params).each do |key, value|
      @open_positions_lists = @open_positions_lists.public_send(key, value) if value.present?
    end
    respond_to do |format|
      format.html
      format.csv { send_data @open_positions_lists.to_csv }
      format.xls { send_data @open_positions_lists.to_xls }
    end

  end

  # GET /open_positions_lists/1
  # GET /open_positions_lists/1.json
  def show
  end

  # GET /open_positions_lists/new
  def new
    @open_positions_list
  end

  # GET /open_positions_lists/1/edit
  def edit
  end

  # POST /open_positions_lists
  # POST /open_positions_lists.json
  def create
    @open_positions_list = OpenPositionsList.new(open_positions_list_params)

    respond_to do |format|
      if @open_positions_list.save
        format.html { redirect_to open_positions_lists_path, notice: 'OPL Eintrag wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: open_positions_lists_path }
      else
        format.html { render :new }
        format.json { render json: @open_positions_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /open_positions_lists/1
  # PATCH/PUT /open_positions_lists/1.json
  def update
    respond_to do |format|
      if @open_positions_list.update(open_positions_list_params)
        format.html { redirect_to open_positions_lists_path, notice: 'Open positions list was successfully updated.' }
        format.json { render :show, status: :ok, location: open_positions_lists_path }
      else
        format.html { render :edit }
        format.json { render json: @open_positions_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /open_positions_lists/1
  # DELETE /open_positions_lists/1.json
  def destroy
    @open_positions_list.destroy
    respond_to do |format|
      format.html { redirect_to open_positions_lists_url, notice: 'Open positions list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    OpenPositionsList.import(params[:file])
  
    redirect_to root_url, notice: 'OPL imported.'
  end

  private
    
    # A list of the param names that can be used for filtering the Product list
    def filtering_params(params)
      params.slice(:shortlist, :client, :category, :updated_at, :costmodel, :state, :prio)
    end
    
    def sort_column
      OpenPositionsList.column_names.include?(params[:sort]) ? params[:sort] : "number"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
  
    # Use callbacks to share common setup or constraints between actions.
    def set_open_positions_list
      @open_positions_list = OpenPositionsList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def open_positions_list_params
      params.require(:open_positions_list).permit(:shortlist, :number, :summary, :description, :option, :component, :category, :prio, :responsible, :state, :costmodel, :affects_version, :issue_ticket, :ticket_text, :notes, :in_sprint, :client)
    end
    
    def open_position_list_number_new
      @open_positions_list = OpenPositionsList.last
      if @open_positions_list == nil
        @open_positions_list = OpenPositionsList.new
        @open_positions_list.number = 1
      else
        @open_positions_list = OpenPositionsList.new
        @open_positions_list.number = OpenPositionsList.last[:number] += 1
      end
    end
end

app/helpers/open_positions_lists_helper.rb
module OpenPositionsListsHelper
end

app/views/open_positions_lists/_edit_form.html.erb
<%= form_for(open_positions_list) do |f| %>
  <% if open_positions_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(open_positions_list.errors.count, "error") %> prohibited this open_positions_list from being saved:</h2>

      <ul>
      <% open_positions_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-inline">
    <div class="form-group">

      <div class="field">
        <%= f.label :number %>
        <%= f.number_field :number, class: 'form-control' %>
      </div>
    
      <div class="field">
        <%= f.text_area :summary, placeholder: "Bezeichnung / Zusammenfassung / Kennung vom Kunden", class: 'form-control'  %>
      </div>
    
      <div class="field">
        <%= f.text_area :description, placeholder: "Ausführlichere Beschreibung der Anforderung", class: 'form-control'  %>
      </div>
    
      <div class="field">
        <%= f.text_area :option, placeholder: "Optionales Feld für Ergänzungen, Kundenanmerkungen, Abmachungen, etc.", class: 'form-control'  %>
      </div>
      
      <!-- Shortlist Selector -->
      <div class="btn btn-lg dropdown">
        Auf die Shortlist setzen? &nbsp; &nbsp;
        <%= f.select :shortlist, ['Ja', 'Nein'], :prompt => "Auf die Shortlist?", class: 'form-control' %>
        &nbsp;&nbsp;&nbsp;&nbsp; | 
      </div>
      
      <!-- Komponente Selector -->
      <div class="btn btn-lg dropdown">
        <%= f.select :component, ['Facebook', 'Twitter', 'GuteFrage','Youtube', 'Instagram', 'Foren', 'anderes SN (s. Beschreibung)', 'Agent Desktop', 'Overview Panel', 'Detail Panel', 'Statistik', 'FAQ', 'Publishing', 'Config', 'System allgemein', 'Import', 'Filter', 'sonstiges [s. Beschreibung)'], :prompt => "Betrifft Komponente", class: 'form-control'  %>
      </div>
      
      <!-- Kategorie Selector -->
      <div class="btn btn-lg dropdown">
        <%= f.select :category, ['FEATURE', 'BUG', 'IMPROVEMENT', 'PROJECT', 'STOPPED'], :prompt => "Kategorie wählen", class: 'form-control' %>
      </div>
      
      <!-- Prio Selector -->
      <div class="btn btn-lg dropdown">
        <%= f.select :prio, ['TRIVIAL', 'MINOR', 'MAJOR', 'CRITICAL', 'BLOCKER'], :prompt => "Priorisierung wählen", class: 'form-control'  %>
      </div>
      
      <!-- Verantwortlichkeit Selector -->
      <div class="btn btn-lg dropdown">
        <%= f.select :responsible, ['PO', 'QM', 'PL'], :prompt => "Zuständigkeit wählen", class: 'form-control'  %>
      </div>
      
      <!-- Status Selector -->
      <div class="btn btn-lg dropdown">
        <%= f.select :state, ['TO-DO', 'ANALYSIS', 'IN PROGRESS', 'QA', 'DONE', 'REJECTED'], :prompt => "Aktueller Status", class: 'form-control'  %>
      </div>
      
      <!-- Kostenmodell Selector -->
      <div class="btn btn-lg dropdown">
        <%= f.select :costmodel, ['Roadmap', 'Cost-Sharing', 'Kundenprojekt'], :prompt => "Kostenmodell angeben", class: 'form-control'  %>
      </div>
    
      <div class="field">
        <%= f.text_field :affects_version, placeholder: "Affected Versions", class: 'form-control'  %>
      </div>
      
      <div class="field">
        <%= f.text_field :issue_ticket, placeholder: "Ticket-Nummer in JIRA", class: 'form-control'  %>
      </div>
    
      <div class="field">
        <%= f.text_area :ticket_text, placeholder: "Text des Tickets", class: 'form-control'  %>
      </div>
    
      <div class="field">
        <%= f.text_area :notes, placeholder: "Zusätzliche Notizen", class: 'form-control'  %>
      </div>
    
      <div class="field">
        <%= f.text_field :in_sprint, placeholder: "Umgestezt in Sprint XYZ", class: 'form-control'  %>
      </div>
    
      <div class="btn btn-success">
        <%= f.submit "Neue Position erstellen" %>
      </div>
    </div>
  </form>
  
<% end %>

app/views/open_positions_lists/copy_index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Open Positions Lists</h1>
</div>

<section class="full-width center">
  
  <div >

  <table class="table table-striped table-sm table-hover sortable">
    <thead style="background-color: #E6FFB4;">
      <tr>
        <th>Shortlist</th>
        <th>Number</th>
        <th>Summary</th>
        <th>Description</th>
        <th>Option</th>
        <th>Component</th>
        <th>Category</th>
        <th>Prio</th>
        <th>Responsible</th>
        <th>State</th>
        <th>Costmodel</th>
        <th>Affects version</th>
        <th>Issue ticket</th>
        <th>Ticket text</th>
        <th>Notes</th>
        <th>In sprint</th>
        <th colspan="1"></th>
      </tr>
    </thead>
  
    <tbody>
      
      <% @open_positions_lists.each do |open_positions_list| %>
        <%= form_for(open_positions_list) do |f| %>
        <tr>
          <!-- <td>< - %= open_positions_list.shortlist %> </td> -->
          <td class="btn btn-xs dropdown-xs"><%= f.select :shortlist, ['Ja', 'Nein'], class: 'form-control'%> </td>
          <td><%= open_positions_list.number %></td>
          <td><%= open_positions_list.summary %></td>
          <td><%= open_positions_list.description %></td>
          <td><%= open_positions_list.option %></td>
          <td><%= open_positions_list.component %></td>
          <td><%= open_positions_list.category %></td>
          <td><%= open_positions_list.prio %></td>
          <td><%= open_positions_list.responsible %></td>
          <td><%= open_positions_list.state %></td>
          <td><%= open_positions_list.costmodel %></td>
          <td><%= open_positions_list.affects_version %></td>
          <td><%= open_positions_list.issue_ticket %></td>
          <td><%= open_positions_list.ticket_text %></td>
          <td><%= open_positions_list.notes %></td>
          <td><%= open_positions_list.in_sprint %></td>
          <td>
            <ul style="list-style-type:none">
              <li><%= link_to 'Show', open_positions_list %></li>
              <li><%= link_to 'Edit', edit_open_positions_list_path(open_positions_list) %></li>
              <li><%= link_to 'Destroy', open_positions_list, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
</div>
  <div>
  <%= link_to 'Neue Position anlegen', new_open_positions_list_path, class: 'btn btn-success' %>
</div>


  <br>
  <br>
  <hr class="padding-bottom-70">
</section>

app/views/open_positions_lists/edit.html.erb
<div class="container">
  <h1>Editing Open Positions List</h1>
  
  <%= render 'form', open_positions_list: @open_positions_list %>
  
  <%= link_to 'Show', @open_positions_list %> |
  <%= link_to 'Back', open_positions_lists_path %>
  <br><br><br>
</div>

app/views/open_positions_lists/index.html.erb
<div class="container-opl">

  <p id="notice"><%= notice %></p>
  
  <h1>Open Topics List</h1>
  
  <section>
            <br>
    <div class="row">
      <div class="col-md-2">
        <%= link_to 'Neue Position anlegen', new_open_positions_list_path, class: 'btn btn-default' %><br><br>
      </div>
      <form>
        <div>
          <span>
            <select id="men-client" class="btn btn-default">
                <option value="">Client Filter</option>
                <option value="All">All</option>
                <option value="O2">O2</option>
                <option value="Telefonica">Telefonica</option>
            </select>
          </span>
          <span> 
            <select id="men-category" class="btn btn-default">
                <option value="">Category Filter</option>
                <option value="All">All</option>
                <option value="FEATURE">FEATURE</option>
                <option value="BUG">BUG</option>
                <option value="IMPROVEMENT">IMPROVEMENT</option>
                <option value="PROJECT">PROJECT</option>
                <option value="STOPPED">STOPPED</option>
            </select>
          </span>
          <span> 
            <select id="men-prio" class="btn btn-default">
                <option value="">Priority Filter</option>
                <option value="All">All</option>
                <option value="TRIVIAL">TRIVIAL</option>
                <option value="MINOR">MINOR</option>
                <option value="MAJOR">MAJOR</option>
                <option value="CRITICAL">CRITICAL</option>
                <option value="BLOCKER">BLOCKER</option>
            </select>
          </span>
          <span> 
            <select id="men-state" class="btn btn-default">
                <option value="">State Filter</option>
                <option value="All">All</option>
                <option value="NEW">NEW</option>
                <option value="TO-DO">TO-DO</option>
                <option value="ANALYSIS">ANALYSIS</option>
                <option value="IN PROGRESS">IN PROGRESS</option>
                <option value="QA">QA</option>
                <option value="DONE">DONE</option>
                <option value="REJECTED">REJECTED</option>
            </select>
          </span>
        </div>
      </form>
    </div>
  
    <div class="row">
        <table class="pretty table table-striped table-sm table-hover">
            <thead style="background-color: YellowGreen; ", class="table-head header">
              <tr>
                <th class="col-sl"><%= sortable "shortlist", "Short List" %></th>
                <th class="col-id"><%= sortable "id" %></th>
                <th class="col-no"><%= sortable "number", "No" %></th>
                <th class="col-su"><%= sortable "summary" %></th>
                <th class="col-ds"><%= sortable "description" %></th>
                <th class="col-op"><%= sortable "option" %></th>
                <th class="col-co"><%= sortable "component" %></th>
                <th class="col-ca"><%= sortable "category" %></th>
                <th class="col-pr"><%= sortable "prio" %></th>
                <th class="col-rp"><%= sortable "responsible", "Resp." %></th>
                <th class="col-st"><%= sortable "state" %></th>
                <th class="col-cm"><%= sortable "costmodel" %></th>
                <th class="col-av"><%= sortable "affects_version" %></th>
                <th class="col-it"><%= sortable "issue_ticket" %></th>
                <th class="col-tt"><%= sortable "ticket_text" %></th>
                <th class="col-nt"><%= sortable "notes" %></th>
                <th class="col-is"><%= sortable "in_sprint" %></th>
                <th class="col-is"><%= sortable "updated_at" %></th>
                <th class="col-is"><%= sortable "client" %></th>
                <th colspan="" class="sorttable_nosort"></th>
              </tr>
            </thead>
          
            <tbody>
              
              <% @open_positions_lists.each do |open_positions_list| %>
      
                <%= form_for(open_positions_list) do |f| %>
                <tr>
                  <!--<td>< %= best_in_place open_positions_list, :shortlist, as: :checkbox, :collection => [["No", false], ["Yes!", true]]  %></td>-->
                  <td><%= best_in_place open_positions_list, :shortlist, as: :select, :collection => [[false, "No!"], [true, "Yes!"]]  %></td>
                  <!--<td>< %= open_positions_list.shortlist %></td>-->
                  <td><%= open_positions_list.id %></td>
                  <td><%= open_positions_list.number %></td>
                  <td><%= best_in_place open_positions_list, :summary, :as => :textarea  %></td>
                  <td><%= best_in_place open_positions_list, :description, :as => :textarea %></td>
                  <td><%= best_in_place open_positions_list, :option, :as => :textarea,
                                                                  :place_holder => "Optionale Notizen eintragen..."  %></td>
                  <td><%= best_in_place open_positions_list, :component, as: :select, 
                                                            :collection => [["Facebook", "Facebook"], 
                                                            ["Gute Frage", "Gute Frage"], 
                                                            ["Youtube", "Youtube"], 
                                                            ["Instagram", "Instagram"], 
                                                            ["Foren", "Foren"], 
                                                            ["anderes SN (s. Beschreibung)", "anderes SN (s. Beschreibung)"],
                                                            ["Agent Desktop", "Agent Desktop"],
                                                            ["Overview Panel", "Overview Panel"],
                                                            ["Detail Panel", "Detail Panel"],
                                                            ["Statistik", "Statistik"],
                                                            ["FAQ", "FAQ"],
                                                            ["Publishing", "Publishing"],
                                                            ["Config", "Config"],
                                                            ["System allgemein", "System allgemein"],
                                                            ["Import", "Import"],
                                                            ["Filter", "Filter"],
                                                            ["sonstiges (s. Beschreibung)", "sonstiges (s. Beschreibung)"]], 
                                                                  :place_holder => "k.A. zur betroffenen Komponente"  %></td>
                  <td><%= best_in_place open_positions_list, :category, 
                                                          as: :select, 
                                                          :collection => [["FEATURE", "FEATURE"], 
                                                          ["BUG", "BUG"], 
                                                          ["IMPROVEMENT", "IMPROVEMENT"], 
                                                          ["PROJECT", "PROJECT"], 
                                                          ["STOPPED", "STOPPED"]], 
                                                                  :place_holder => "k.A. zur Kategorie" %></td>
                  <td><%= best_in_place open_positions_list, :prio,
                                                          as: :select, 
                                                          :collection => [["TRIVIAL", "TRIVIAL"], 
                                                          ["MINOR", "MINOR"], 
                                                          ["MAJOR", "MAJOR"], 
                                                          ["CRITICAL", "CRITICAL"], 
                                                          ["BLOCKER", "BLOCKER"]], 
                                                                  :place_holder => "k.A. zur Priorität" %></td>
                  <td><%= best_in_place open_positions_list, :responsible,
                                                          as: :select, 
                                                          :collection => [["PO", "PO"], 
                                                          ["PL", "PL"], 
                                                          ["QM", "QM"]], 
                                                                  :place_holder => "k.A." %></td>
                  <td><%= best_in_place open_positions_list, :state, 
                                                          as: :select, 
                                                          :collection => [["NEW", "NEW"], 
                                                          ["TO-DO", "TO-DO"], 
                                                          ["ANALYSIS", "ANALYSIS"], 
                                                          ["OPEN", "OPEN"], 
                                                          ["IN PROGRESS", "IN PROGRESS"], 
                                                          ["QA", "QA"], 
                                                          ["DONE", "DONE"], 
                                                          ["REJECTED", "REJECTED"]], 
                                                                  :place_holder => "k.A. zum Status" %></td>
                  <td><%= best_in_place open_positions_list, :costmodel, 
                                                          as: :select, 
                                                          :collection => [["ROADMAP", "ROADMAP"], 
                                                          ["COST-SHARING", "COST-SHARING"], 
                                                          ["CLIENT-PROJECT", "CLIENT-PROJECT"]], 
                                                                  :place_holder => "k.A. zum Cost-Model" %></td>
                  <td><%= best_in_place open_positions_list, :affects_version, 
                                                                  :place_holder => "Betroffene Versionen eintragen..." %></td>
                  <td><%= best_in_place open_positions_list, :issue_ticket, 
                                                             input_html: { value: "SC-" },
                                                                  :place_holder => "Ticket-Nr. eintragen..." %></td>
                  <td><%= best_in_place open_positions_list, :ticket_text, :as => :textarea, 
                                                                  :place_holder => "Ticket-Text eintragen..." %></td>
                  <td><%= best_in_place open_positions_list, :notes, :as => :textarea, 
                                                                  :place_holder => "Notizn..." %></td>
                  <td><%= best_in_place open_positions_list, :in_sprint, 
                                                                  :place_holder => "In Sprint..." %></td>
                  <td><%= open_positions_list.updated_at.strftime("%d. %b %Y") %></td>
                  <td><%= best_in_place open_positions_list, :client,
                                                          as: :select, 
                                                          :collection => [["O2", "O2"], ["Telefonica", "Telefonica"]], 
                                                          :place_holder => "k.A." %></td>
                  <td>
                    <ul style="list-style-type:none">
                      <!-- 'Show' <li>< %= link_to '', open_positions_list, class: 'glyphicon glyphicon-eye-open button', style: 'color:YellowGreen ;' %></li>   -->
                      <!-- 'Edit' <li>< %= link_to '', edit_open_positions_list_path(open_positions_list), class: 'glyphicon glyphicon-pencil button', style: 'color:YellowGreen ;' %></li>  -->
                      <li><%= link_to '', open_positions_list, class: 'glyphicon glyphicon-trash button', style: 'color:YellowGreen ;', method: :delete, data: { confirm: 'Are you sure?' } %></li> <!-- 'Destroy' -->
                    </ul>
                  </td>
                </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
      </div>
    <div class="row">
      <div>
      <br>
        <%= link_to 'Neue Position anlegen', new_open_positions_list_path, class: 'btn btn-success' %><br><br>
      </div>
      
      <p>
        Download:
        <%= link_to "CSV", open_positions_lists_path(format: "csv") %> |
        <%= link_to "Excel", open_positions_lists_path(format: "xls") %>
      </p>
      
      <h4>Import OPL</h4>
        <%= form_tag import_open_positions_lists_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Import" %>
        <% end %>
    </div>
    
    <br>
    <br>
    <hr>
  </section>
</div>

app/views/open_positions_lists/new.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
    <div class="row">
      <div >
        <h1>New Topic</h1><br>
      </div>

      <div>
        <div class="row">
          <%= render 'form', open_positions_list: @open_positions_list %> 
        </div>
      </div>
  
    </div>
    <div >
      
      <br>
      <br>
      <br>
    </div>
</div>

app/views/open_positions_lists/new_short.html.erb
<h1>New Open Positions List</h1>
<div class="container">
        <%= render 'new_short_form', open_positions_list: @open_positions_list %>
</div>


<%= link_to 'Back', open_positions_lists_path %>

app/views/open_positions_lists/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Number:</strong>
    <%= @open_positions_list.number %>
  </p>
  
  <p>
    <strong>Summary:</strong>
    <%= @open_positions_list.summary %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%= @open_positions_list.description %>
  </p>
  
  <p>
    <strong>Option:</strong>
    <%= @open_positions_list.option %>
  </p>
  
  <p>
    <strong>Component:</strong>
    <%= @open_positions_list.component %>
  </p>
  
  <p>
    <strong>Category:</strong>
    <%= @open_positions_list.category %>
  </p>
  
  <p>
    <strong>Prio:</strong>
    <%= @open_positions_list.prio %>
  </p>
  
  <p>
    <strong>Responsible:</strong>
    <%= @open_positions_list.responsible %>
  </p>
  
  <p>
    <strong>State:</strong>
    <%= @open_positions_list.state %>
  </p>
  
  <p>
    <strong>Costmodel:</strong>
    <%= @open_positions_list.costmodel %>
  </p>
  
  <p>
    <strong>Affects version:</strong>
    <%= @open_positions_list.affects_version %>
  </p>
  
  <p>
    <strong>Issue ticket:</strong>
    <%= @open_positions_list.issue_ticket %>
  </p>
  
  <p>
    <strong>Ticket text:</strong>
    <%= @open_positions_list.ticket_text %>
  </p>
  
  <p>
    <strong>Notes:</strong>
    <%= @open_positions_list.notes %>
  </p>
  
  <p>
    <strong>In sprint:</strong>
    <%= @open_positions_list.in_sprint %>
  </p>
  
  <%= link_to 'Edit', edit_open_positions_list_path(@open_positions_list) %> |
  <%= link_to 'Back', open_positions_lists_path %>
</div>