config/routes.rb
Rails.application.routes.draw do
  root "shortlist#index"

  resources :open_positions_lists
  resources :shortlist
  
  resources :open_positions_lists do
    collection do
      post :import
    end
  end
  
  # get 'static_pages/shortlist'

  get 'static_pages/about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # root "shortlist#index"

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/layouts/_footer.html.erb
<div class="container">
  <br>
  <h1>Example page footer <small>Subtext for footer</small></h1>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-fixed-top navbar-light" style="background-color: #8cbf26;" role="navigation">
    <div class="container">
      <div class="row">
      <div>
        <a class="navbar-brand" style="color: #fff;" href="#">openTOPICS</a>
      </div>
      <br>
      <div class="nav navbar-nav pull-right">
        <a class="nav-item nav-link" href="#"><%= link_to 'Liste', open_positions_lists_path, {style: "color: #fff"} %></a>
        <a class="nav-item nav-link" href="#"><%= link_to " | ShortList", root_path, {style: "color: #fff"} %></a>
        <a class="nav-item nav-link" href="#"><%= link_to ' | About', static_pages_about_path, {style: "color: #fff"} %></a>
      </div>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open Topics List</title>

    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    
  </head>
  <body>
    
    <div class="page-wrap">
      
      <div class="row">
        <div>
          <div>
            <%= render "layouts/navigation" %>
          </div>
        </div>
        <div class="row">
          <div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    
    <footer class="site-footer">
        <div class="row">
          <div>
            <%= render "layouts/footer" %>
          </div>
        </div>
    
    </footer>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'jquery-2.2.3.min' %>
    <%= javascript_include_tag 'jquery-ui.min' %>
    <%= javascript_include_tag 'best_in_place' %>
    <%= javascript_include_tag 'best_in_place.jquery-ui' %>
    <%= javascript_include_tag 'best_in_place.purr' %>
    
  </body>
</html>